"""Added nullable field for user

Revision ID: ac8e3d858e55
Revises: c7af46424c6a
Create Date: 2024-01-28 21:33:59.683212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac8e3d858e55'
down_revision: Union[str, None] = 'c7af46424c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_feedback',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'dateTimeFeedback',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'dateTimeFeedback',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'id_feedback',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
