"""Added nullable field for feedback

Revision ID: da3078379a72
Revises: ac8e3d858e55
Create Date: 2024-01-28 22:29:58.481750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3078379a72'
down_revision: Union[str, None] = 'ac8e3d858e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('feedback', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feedback', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
